[env:esp32dev] 
platform = espressif32
board = esp32dev
board_build.filesystem = littlefs
board_build.partitions = partitions.csv
framework = arduino
monitor_speed = 115200

lib_deps = 
	https://github.com/someweisguy/esp_dmx
	bblanchon/ArduinoJson
	espressif/ESP32HTTPUpdateServer

extra_scripts = pre:prepare_fs.py
		post:upload_fs_auto.py


build_flags = -DCORE_DEBUG_LEVEL=0